version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - python -m pip install -U poetry poetry-plugin-export
      - python -m poetry export -f requirements.txt -o req-docs.txt -E docs
    pre_build:
      - sphinx-apidoc --force --module-first --separate -o docs/source/api sheap
      - test -f ./scripts/yaml_to_rst.py && python ./scripts/yaml_to_rst.py || echo "Skipping yaml_to_rst.py"
      - test -f ./scripts/clean_rst.py && python ./scripts/clean_rst.py || echo "Skipping clean_rst.py"
      - test -f ./scripts/make_available_continuum_profiles.py && python ./scripts/make_available_continuum_profiles.py || echo "Skipping make_available_continuum_profiles.py"
      - test -f ./scripts/make_start.py && python ./scripts/make_start.py || echo "make_start.py"
      - python ./scripts/visualize-ga-workflow.py > docs/cicd_mermaid.md 2>/dev/null || echo "Skipping GA workflow visualization"
      - python ./scripts/visualize-dockerfile.py > docs/dockerfile_mermaid.md 2>/dev/null || echo "Skipping Dockerfile visualization"
#make_start.py
python:
  install:
    - method: pip
      path: .
    - requirements: req-docs.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats: [htmlzip, pdf, epub]
